name: "Foo"

on:
  pull_request:

jobs:
  foo:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13-dev"

      - uses: mkniewallner/maturin-action@7f596ace86ff6ff2331585f772d8746888237b6a
        with:
          command: help
