name: "Foo"

on:
  pull_request:

jobs:
  foo:
    name: Foo
    runs-on: macos-12
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11-dev"

      - name: Bootstrap poetry
        run: curl -sL https://install.python-poetry.org | python - -y
