name: "Foo"

on:
  pull_request:

jobs:
  foo:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13-dev"

      - uses: PyO3/maturin-action@v1
        with:
          command: help
