name: "Foo"

on:
  push:
    branches-ignore:
      - main
  pull_request_target:
    types:
      - labeled
      - synchronize

jobs:
  foo:
    name: Foo
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.push.repository.full_name }}
      - run: echo ${{ github.repository }}
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
