name: "Foo"

on:
  push:
    branches-ignore:
      - main
  pull_request_target:
    types:
      - labeled
      - synchronize

jobs:
  foo:
    name: Foo
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'safe'))
      || (github.event_name == 'push' && github.event.push.repository.full_name == github.repository)
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
